# Generated by Django 4.2 on 2024-08-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, to='blog_data.tag')),
            ],
        ),
    ]
