# Generated by Django 4.2.3 on 2024-08-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_data', '0002_tag_postdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
